---
- name: "{{ ansible_os_family }}: Install apt dependencies for upgrade command"
  apt: 
    name: "{{item}}"
    state: installed
  with_items:
    - "python-minimal"
    - "aptitude"

- name: "{{ ansible_os_family }}: Update and upgrade apt packages"
  become: true
  apt:
    upgrade: yes
    update_cache: yes
    cache_valid_time: 86400 #One day

- name: "{{ ansible_os_family }}: Update and Full upgrade apt packages"
  become: true
  apt:
    upgrade: full
    update_cache: yes
    cache_valid_time: 86400 #One day

- name: "{{ ansible_os_family }}: Update and Dist upgrade apt packages"
  become: true
  apt:
    upgrade: dist
    update_cache: yes
    cache_valid_time: 86400 #One day
