---
- gather_facts: False
  hosts: server1
  vars:
    store_pass: myPass
    cert_dir: /weblogic/certificates
    weblogic_admin: wlogic
    weblogic_group: dba
    cert_details:
      server1:
        dname: "/OU=server1 OU/O=server1 O/L=Server1 L/ST=server1 ST/C=EU"
      server2:
        dname: "/OU=server2 OU/O=server2 O/L=Server2 L/ST=server2 ST/C=EU"
  tasks:
    - name: Create certificates folder
      raw: mkdir -p {{ cert_dir }}

    - name: Create Key and Keystore
      raw: openssl genrsa -des3 -passout pass:{{ store_pass }} -out {{ cert_dir }}/{{ inventory_hostname }}.key 2048

    - name: Create certificate request
      raw: openssl req -new -key {{ cert_dir }}/`hostname`.key -out {{ cert_dir }}/{{ inventory_hostname }}.csr -subj "/CN={{ inventory_hostname }}{{ cert_details[inventory_hostname].dname }}" -passin pass:{{ store_pass }}

    - name: List created certificate request
      raw: openssl req -noout -text -in {{ cert_dir }}/{{ inventory_hostname }}.csr

    - name: Change ownership for certificates folder
      raw: chown -R {{ weblogic_admin }}:{[ weblogic_group }} {{ cert_dir }}

    - name: List all files created
      raw: ll {{ cert_dir }}
